/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.LayoutManager;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author asus
 */
public class PanelHalamanTabel extends javax.swing.JPanel {
    private JPanel panel;
    private koneksi.KoneksiOracleThinClient kon;
    private String judul;

    /**
     * Creates new form PanelHalaman1
     */
    public PanelHalamanTabel() {
        initComponents();
    }
    
    public PanelHalamanTabel(String [][] data, String [] kolom) {
        this();
        tampilkanDataKeTabel(data, kolom);
    }
     public void DapatDataDariTable(int row){
        
  }
    public void tampilkanDataKeTabel(String [][] data, String [] kolom) {
        //kosongkan tabel terlebih dulu
       
            ((DefaultTableModel) jTable1.getModel()).setColumnCount(0);
        int row = jTable1.getRowCount();
        for (int i = 0; i < row; i++) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(0);
        }
        
        //isi tabel dgn data baru
        for (int b=0; b<kolom.length; b++) {
            ((DefaultTableModel)jTable1.getModel()).addColumn(kolom[b]);
        }
        for (int a=0; a<data.length; a++)  {
            ((DefaultTableModel)jTable1.getModel()).addRow(data[a]);
        }
        for (int b=0; b<kolom.length; b++) {
            packColumn(jTable1, b, 5);
        }
    }
    
    public void tampilkanPanelAtribut(JPanel _panel) {
        this.panel = _panel;
        Component [] komponens = panelAtribut.getComponents();
        for (Component komponen: komponens) {
            panelAtribut.remove(komponen);
        }
        panelAtribut.add(panel);        
    }
    
    public static void packColumn(JTable table, int vColIndex, int margin) {
        DefaultTableColumnModel colModel = (DefaultTableColumnModel)table.getColumnModel();
        TableColumn col = colModel.getColumn(vColIndex);
        int width = 0;

        // Get width of column header
        TableCellRenderer renderer = col.getHeaderRenderer();
        if (renderer == null) {
            renderer = table.getTableHeader().getDefaultRenderer();
        }
        java.awt.Component comp = renderer.getTableCellRendererComponent(
            table, col.getHeaderValue(), false, false, 0, 0);
        width = comp.getPreferredSize().width;

        // Get maximum width of column data
        for (int r=0; r<table.getRowCount(); r++) {
            renderer = table.getCellRenderer(r, vColIndex);
            comp = renderer.getTableCellRendererComponent(
                table, table.getValueAt(r, vColIndex), false, false, r, vColIndex);
            width = Math.max(width, comp.getPreferredSize().width);
        }

        // Add margin
        width += 2*margin;

        // Set the width
        col.setPreferredWidth(width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelSIUD = new javax.swing.JPanel();
        panelField = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelAtribut = new javax.swing.JPanel();
        panelKontrol = new javax.swing.JPanel();
        buttonBaru = new Widget.Button();
        buttonInsert = new Widget.Button();
        buttonUpdate = new Widget.Button();
        buttonDelete = new Widget.Button();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(2, 1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);

        panelSIUD.setOpaque(false);
        panelSIUD.setLayout(new java.awt.BorderLayout());

        panelField.setOpaque(false);
        panelField.setLayout(new java.awt.BorderLayout());

        panelAtribut.setLayout(new java.awt.BorderLayout());
        jScrollPane2.setViewportView(panelAtribut);

        panelField.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelSIUD.add(panelField, java.awt.BorderLayout.CENTER);

        panelKontrol.setOpaque(false);
        panelKontrol.setLayout(new java.awt.GridLayout(1, 4));

        buttonBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Empty-Page-64.png"))); // NOI18N
        buttonBaru.setText("Dokumen Baru");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });
        panelKontrol.add(buttonBaru);

        buttonInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Insert documents-64.png"))); // NOI18N
        buttonInsert.setText("Insert");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });
        panelKontrol.add(buttonInsert);

        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Update Document-64.png"))); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        panelKontrol.add(buttonUpdate);

        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete Document Grey-64.png"))); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        panelKontrol.add(buttonDelete);

        panelSIUD.add(panelKontrol, java.awt.BorderLayout.PAGE_END);

        add(panelSIUD);
    }// </editor-fold>//GEN-END:initComponents

    public void setKoneksi(koneksi.KoneksiOracleThinClient _kon, String _judul) {
        kon = _kon;
        judul = _judul;
    }
    
    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        // TODO add your handling code here:
        String query = "insert into BFR_ILN_TMST_PENDAFTAR " +
                       "(KEY_ID, NO_REGISTER, NIDN, NO_TELEPON, NAMA_PT1, " +
                       " NOMOR_SK, TIM_PENILAI, ID_PENGUSUL, STATUS, " + 
                       " NO_BERITA_ACARA, STATUS_SK) " +
                       " values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        if (judul.equals("Master Pendaftar")) {
            System.out.println("master pendaftar");
            int hasil = kon.insertUpdateDeleteData(query, 
                    ((PanelMasterPendaftar)panel).dapatkanNilaiUntukInsert() );
            if (hasil == 1) {
               query = "select KEY_ID, NO_REGISTER, NIDN, NO_TELEPON, NAMA_PT1, " +
                        " NOMOR_SK, TIM_PENILAI, ID_PENGUSUL, STATUS, " + 
                        " NO_BERITA_ACARA, STATUS_SK " +
                        " from BUFF01_TEST_PDPT.BFR_ILN_TMST_PENDAFTAR order by KEY_ID desc "; 
               kon.selectData(query);
               tampilkanDataKeTabel(kon.dapatkanData(), kon.dapatkanKolom());
            }
        }
    }//GEN-LAST:event_buttonInsertActionPerformed

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
        ((PanelMasterPendaftar)panel).persiapanEntriDataBaru();
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        String query = "update BFR_ILN_TMST_PENDAFTAR "+
                "SET NO_REGISTER=?"
                + " where KEY_ID=?";
        if (judul.equals("Master Pendaftar")) {
            System.out.println("master pendaftar");
            int hasil = kon.insertUpdateDeleteData(query, 
                    ((PanelMasterPendaftar)panel).dapatkanNilaiUntukupdate() );
            if (hasil == 1) {
               query = "select KEY_ID, NO_REGISTER, NIDN, NO_TELEPON, NAMA_PT1, " +
                        " NOMOR_SK, TIM_PENILAI, ID_PENGUSUL, STATUS, " + 
                        " NO_BERITA_ACARA, STATUS_SK " +
                        " from BUFF01_TEST_PDPT.BFR_ILN_TMST_PENDAFTAR order by KEY_ID desc "; 
               kon.selectData(query);
               tampilkanDataKeTabel(kon.dapatkanData(), kon.dapatkanKolom());
            }
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        String query = "delete from BFR_ILN_TMST_PENDAFTAR where Key_id=?";
        if (judul.equals("Master Pendaftar")) {
            System.out.println("master pendaftar");
            int hasil = kon.insertUpdateDeleteData(query, 
                    ((PanelMasterPendaftar)panel).dapatkanNilaiUntukDelete() );
            if (hasil == 1) {
               query = "select KEY_ID, NO_REGISTER, NIDN, NO_TELEPON, NAMA_PT1, " +
                        " NOMOR_SK, TIM_PENILAI, ID_PENGUSUL, STATUS, " + 
                        " NO_BERITA_ACARA, STATUS_SK " +
                        " from BUFF01_TEST_PDPT.BFR_ILN_TMST_PENDAFTAR order by KEY_ID desc "; 
               kon.selectData(query);
               tampilkanDataKeTabel(kon.dapatkanData(), kon.dapatkanKolom());
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
       String data[] = new String[15];
       for(int i=0;i<=10;i++){
           data[i]=jTable1.getValueAt(row, i).toString();
           System.out.println("DATA "+data[i]);
       }
       ((PanelMasterPendaftar)panel).persiapanUpdateData(data);
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Widget.Button buttonBaru;
    private Widget.Button buttonDelete;
    private Widget.Button buttonInsert;
    private Widget.Button buttonUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelAtribut;
    private javax.swing.JPanel panelField;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JPanel panelSIUD;
    // End of variables declaration//GEN-END:variables
}
