/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

/**
 *
 * @author asus
 */
public class PanelPilihTabel extends javax.swing.JPanel {
    private TanpaBingkai3 miniku;
    private String query;

    /**
     * Creates new form PanelHalaman1
     */
    public PanelPilihTabel() {
        initComponents();
    }
    
    
    public PanelPilihTabel(TanpaBingkai3 mini) {
        this();
        miniku = mini;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new Widget.Button();
        button2 = new Widget.Button();
        button3 = new Widget.Button();
        button5 = new Widget.Button();
        button4 = new Widget.Button();
        button6 = new Widget.Button();
        button8 = new Widget.Button();
        button7 = new Widget.Button();
        button9 = new Widget.Button();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(960, 600));
        setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pendaftaran_mhs_64.png"))); // NOI18N
        button1.setText("Master Pendaftar");
        button1.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Book Library-64.png"))); // NOI18N
        button2.setText("Master Mata Kuliah");
        button2.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mahasiswa_64.png"))); // NOI18N
        button3.setText("Master Mahasiswa");
        button3.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi_kuliah_mhs_64.png"))); // NOI18N
        button5.setText("Transaksi Kuliah Mahasiswa");
        button5.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        add(button5);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lessons-64.png"))); // NOI18N
        button4.setText("Transaksi Aktivitas Mengajar Dosen");
        button4.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        add(button4);

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi_nilai_sem_mhs_64.png"))); // NOI18N
        button6.setText("Transaksi Nilai Semester Mahasiswa");
        button6.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        add(button6);

        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/prev_mini.png"))); // NOI18N
        add(button8);

        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        add(button7);

        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next_mini.png"))); // NOI18N
        add(button9);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        query = "select KEY_ID, NO_REGISTER, NIDN, NO_TELEPON, NAMA_PT1, " +
                        " NOMOR_SK, TIM_PENILAI, ID_PENGUSUL, STATUS, " + 
                        " NO_BERITA_ACARA, STATUS_SK " +
                        " from BUFF01_TEST_PDPT.BFR_ILN_TMST_PENDAFTAR order by KEY_ID desc ";
        miniku.persiapanAmbilData(query, "Master Pendaftar");
    }//GEN-LAST:event_button1ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        query = "SELECT e.* " +
          " FROM ( " + 
              " select KEY_ID, LAPOR_DATA_JENIS_KEY_ID, SUMBER_DATA_KEY_ID, " +
                     " SUMBER_UPLOAD_KEY_ID, VALIDASI_IS_VALID, " +  
                     " KODE_MATA_KULIAH, TAHUN_PELAPORAN " +
                     " KODE_PERGURUAN_TINGGI, KODE_PROGRAM_STUDI, " +
                     " KODE_JENJANG_STUDI, NAMA_MATA_KULIAH, SEMESTER " +
                     " SEMESTER_PELAPORAN " +
              " from BFR_TMST_MATA_KULIAH " +
              " order by KODE_MATA_KULIAH " +
          ") e " + 
          " WHERE ROWNUM < 5 ";
        miniku.persiapanAmbilData(query, "Master MATA KULIAH");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        query = "SELECT e.* " +
          " FROM ( " + 
              " select KEY_ID, LAPOR_DATA_JENIS_KEY_ID, SUMBER_DATA_KEY_ID, " +
                     " SUMBER_UPLOAD_KEY_ID, VALIDASI_IS_VALID, " +  
                     " KODE_PERGURUAN_TINGGI, KODE_PROGRAM_STUDI, " +
                     " NIM, NAMA_MAHASISWA, TEMPAT_LAHIR, " +
                     " KODE_JENJANG_PENDIDIKAN, TANGGAL_LAHIR, JENIS_KELAMIN " +
              " from BFR_TMST_MAHASISWA " +
              " order by NIM " +
          ") e " + 
          " WHERE ROWNUM < 5 ";
        miniku.persiapanAmbilData(query, "Master MAHASISWA");
    }//GEN-LAST:event_button3ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        query = "SELECT e.* " +
          " FROM ( " + 
              " select KEY_ID, LAPOR_DATA_JENIS_KEY_ID, SUMBER_DATA_KEY_ID, " +
                     " SUMBER_UPLOAD_KEY_ID, VALIDASI_IS_VALID, " +  
                     " KODE_KULIAH_MHS, TAHUN_PELAPORAN, " +
                     " KODE_PERGURUAN_TINGGI, KODE_PROGRAM_STUDI, " +
                     " KODE_JENJANG_STUDI, NIM, STATUS_MAHASISWA, IPS, " +
                     " SKS_SEMESTER, SEMESTER_PELAPORAN " +
              " from BFR_TRAN_KULIAH_MHS " +
              " order by NIM, KODE_KULIAH_MHS " +
          ") e " + 
          " WHERE ROWNUM < 5 ";
        miniku.persiapanAmbilData(query, "Transaksi KULIAH MAHASISWA");
    }//GEN-LAST:event_button5ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        query = "SELECT e.* " +
          " FROM ( " + 
              " select KEY_ID, LAPOR_DATA_JENIS_KEY_ID, SUMBER_DATA_KEY_ID, " +
                     " SUMBER_UPLOAD_KEY_ID, VALIDASI_IS_VALID, " +  
                     " KODE_MENGAJAR_DOSEN, NIDN, " +
                     " TAHUN_PELAPORAN, KODE_MATA_KULIAH, " +
                     " KODE_KELAS, JML_TATAP_MUKA_RENCANA, " +
                     " JML_TATAP_MUKA_REALISASI, " +
                     " SEMESTER_PELAPORAN " +
              " from BFR_TRAN_AKT_MAJAR_DOSEN " +
              " order by NIDN, KODE_MATA_KULIAH " +
          ") e " + 
          " WHERE ROWNUM < 5 ";
        miniku.persiapanAmbilData(query, "Transaksi AKTIVITAS MENGAJAR DOSEN");
    }//GEN-LAST:event_button4ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        query = "SELECT e.* " +
          " FROM ( " + 
              " select KEY_ID, LAPOR_DATA_JENIS_KEY_ID, SUMBER_DATA_KEY_ID, " +
                     " SUMBER_UPLOAD_KEY_ID, VALIDASI_IS_VALID, " +  
                     " KODE_NILAI_MHS, KODE_KULIAH_MHS, " +
                     " TAHUN_PELAPORAN, KODE_PERGURUAN_TINGGI, " +
                     " KODE_PROGRAM_STUDI, KODE_JENJANG_PENDIDIKAN, " +
                     " NIM, KODE_MATA_KULIAH, BOBOT_NILAI, " +
                     " KODE_KELAS " +
              " from BFR_TRAN_NILAI_SMT_MHS " +
              " order by NIM, KODE_MATA_KULIAH " +
          ") e " + 
          " WHERE ROWNUM < 5 ";
        miniku.persiapanAmbilData(query, "Transaksi NILAI SEMESTER MAHASISWA");
    }//GEN-LAST:event_button6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Widget.Button button1;
    private Widget.Button button2;
    private Widget.Button button3;
    private Widget.Button button4;
    private Widget.Button button5;
    private Widget.Button button6;
    private Widget.Button button7;
    private Widget.Button button8;
    private Widget.Button button9;
    // End of variables declaration//GEN-END:variables
}
