/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

/**
 *
 * @author asus
 */
public class PanelHalaman1 extends javax.swing.JPanel {
    private TerminalMetroMini3 miniku;
    private TanpaBingkai2 miniku2;
    private String versi;

    /**
     * Creates new form PanelHalaman1
     */
    public PanelHalaman1() {
        initComponents();
    }
    
    public PanelHalaman1(TerminalMetroMini3 mini) {
        this();
        miniku = mini;
        versi = "berbingkai";
    }
    
    public PanelHalaman1(TanpaBingkai2 mini) {
        this();
        miniku2 = mini;
        versi = "tanpabingkai";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMenu1 = new javax.swing.JPanel();
        button1 = new Widget.Button();
        panelMenu1Info = new javax.swing.JPanel();
        label1 = new Widget.Label();
        label2 = new Widget.Label();
        label3 = new Widget.Label();
        label4 = new Widget.Label();
        button2 = new Widget.Button();
        button3 = new Widget.Button();
        button5 = new Widget.Button();
        button4 = new Widget.Button();
        button6 = new Widget.Button();
        button8 = new Widget.Button();
        button7 = new Widget.Button();
        button9 = new Widget.Button();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(4, 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nama Menu");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1);
        add(jLabel2);
        add(jLabel3);

        panelMenu1.setOpaque(false);
        panelMenu1.setLayout(new java.awt.GridLayout(1, 2));

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database_mini.png"))); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelMenu1.add(button1);

        panelMenu1Info.setOpaque(false);
        panelMenu1Info.setLayout(new java.awt.GridLayout(4, 0));

        label1.setForeground(new java.awt.Color(204, 255, 0));
        label1.setText("Masuk ke Pendataan Evaluasi (*)");
        label1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelMenu1Info.add(label1);

        label2.setForeground(new java.awt.Color(204, 255, 0));
        label2.setText("Cabut Notasi (Untuk 1x saja)");
        label2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelMenu1Info.add(label2);

        label3.setForeground(new java.awt.Color(204, 255, 0));
        label3.setText("Re-Index Database");
        label3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelMenu1Info.add(label3);

        label4.setForeground(new java.awt.Color(204, 255, 0));
        label4.setText("View Error Message");
        label4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelMenu1Info.add(label4);

        panelMenu1.add(panelMenu1Info);

        add(panelMenu1);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kegiatan_mini.png"))); // NOI18N
        add(button2);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data_pendukung_mini.png"))); // NOI18N
        add(button3);

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kependidikan2.gif"))); // NOI18N
        add(button5);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evaluasi_utility_mini.png"))); // NOI18N
        add(button4);
        add(button6);

        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/prev_mini.png"))); // NOI18N
        add(button8);
        add(button7);

        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next_mini.png"))); // NOI18N
        add(button9);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("coba ambil data dari trkln");
        String query = "select * from PDPT.\"trkln\"";
        if (versi.equals("berbingkai"))   {
            miniku.persiapanAmbilData(query);            
        } else {
            miniku2.persiapanAmbilData(query);
            miniku2.tambahDataKeVerbose("retrive data: transaksi luar negeri");
        }        
    }//GEN-LAST:event_button1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Widget.Button button1;
    private Widget.Button button2;
    private Widget.Button button3;
    private Widget.Button button4;
    private Widget.Button button5;
    private Widget.Button button6;
    private Widget.Button button7;
    private Widget.Button button8;
    private Widget.Button button9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private Widget.Label label1;
    private Widget.Label label2;
    private Widget.Label label3;
    private Widget.Label label4;
    private javax.swing.JPanel panelMenu1;
    private javax.swing.JPanel panelMenu1Info;
    // End of variables declaration//GEN-END:variables
}
