/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JWindow;

/**
 *
 * @author asus
 */
public class PintuGerbang extends JFrame {
    private String nama, password;
    private TanpaBingkai3 utama;

    /**
     * Creates new form PintuGerbang
     */
    public PintuGerbang() {
        super.setUndecorated(true);
        initComponents();        
        utama = new TanpaBingkai3();             
        
        setSize(568, 219);
        setLocationRelativeTo(null);
        setVisible(true);        
        jTextField1.requestFocus();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        labelKunci = new Widget.Label();
        panelLogin = new javax.swing.JPanel();
        label1 = new Widget.Label();
        jTextField1 = new javax.swing.JTextField();
        label2 = new Widget.Label();
        jPasswordField1 = new javax.swing.JPasswordField();
        button1 = new Widget.Button();
        button2 = new Widget.Button();

        setPreferredSize(new java.awt.Dimension(413, 183));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        labelKunci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Key-64.png"))); // NOI18N
        labelKunci.setBounds(0, 0, 90, 180);
        jDesktopPane1.add(labelKunci, javax.swing.JLayeredPane.DEFAULT_LAYER);

        panelLogin.setOpaque(false);
        panelLogin.setLayout(new java.awt.GridLayout(3, 2, 20, 10));

        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Nama Operator");
        label1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        panelLogin.add(label1);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        panelLogin.add(jTextField1);

        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("Kata Sandi");
        label2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        panelLogin.add(label2);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        panelLogin.add(jPasswordField1);

        button1.setForeground(new java.awt.Color(255, 153, 0));
        button1.setMnemonic('B');
        button1.setText("Batal");
        button1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelLogin.add(button1);

        button2.setForeground(new java.awt.Color(255, 153, 0));
        button2.setMnemonic('L');
        button2.setText("Login");
        button2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelLogin.add(button2);

        panelLogin.setBounds(90, 0, 300, 150);
        jDesktopPane1.add(panelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        nama = jTextField1.getText();
        password = new String(jPasswordField1.getPassword());
        if (nama.equals("operator") && password.equals("rahasia")) {
            utama.setVisible(true);
            this.setVisible(false);
            utama.setNamaOperator(nama);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
         //JOptionPane.showMessageDialog(null, "" + evt.getKeyCode()); 
        if (evt.getKeyCode() == 10) {
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            button2ActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    public static void main(String [] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        PintuGerbang coba = new PintuGerbang();        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Widget.Button button1;
    private Widget.Button button2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private Widget.Label label1;
    private Widget.Label label2;
    private Widget.Label labelKunci;
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables
}
