/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JWindow;
import javax.swing.Timer;
import koneksi.KoneksiOracleThinClient;

/**
 *
 * @author asus
 */
public class TanpaBingkai2 extends JFrame {
    private PanelHalaman1 panelHalaman1;
    private Timer timer;

    /**
     * Creates new form TanpaBingkai
     */
    public TanpaBingkai2() {
        super.setUndecorated(true);
        initComponents();
        inisialisasiLayarTengah();
        layarPenuh();        
        tampilkanJam();
        
        setSize(1366, 768);
    }
    
    public void setNamaOperator(String nama) {
        labelLogin.setText(nama);
        tambahDataKeVerbose(nama + " masuk pada " + new Date().toString());
    }
    
    public void tambahDataKeVerbose(String data) {
        textVerbose.append(data + "\n");
    }
    
    private void inisialisasiLayarTengah() {
        panelHalaman1 = new PanelHalaman1(this);
        panelMetro.add(panelHalaman1);
        
        //nyoba utk tampilkan data ke tabel
        /*
        KoneksiOracleThinClient coba = new KoneksiOracleThinClient();
        coba.kirimQuery("select * from PDPT.\"trkln\"");     
        String [][] data = coba.dapatkanData();
        String [] kolom = coba.dapatkanKolom();
        PanelHalamanTabel panel = new PanelHalamanTabel(data, kolom);
        panelMetro.add(panel);
        * */
    }
    
    public void persiapanAmbilData(String query) {
        KoneksiOracleThinClient coba = new KoneksiOracleThinClient();
        coba.selectData(query);     
        String [][] data = coba.dapatkanData();
        String [] kolom = coba.dapatkanKolom();
        PanelHalamanTabel panel = new PanelHalamanTabel(data, kolom);
        Component komponen = panelMetro.getComponent(0);
        panelMetro.remove(komponen);
        panelMetro.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        panelBesar = new javax.swing.JPanel();
        panelMetro = new javax.swing.JPanel();
        panelKanan = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        labelAvatar = new javax.swing.JLabel();
        tabbedPane1Verbose = new javax.swing.JTabbedPane();
        panelVerbose = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textVerbose = new javax.swing.JTextArea();
        panelWaktu = new javax.swing.JPanel();
        labelWaktu = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelBawah = new javax.swing.JPanel();
        label1 = new Widget.Label();
        panelKiri = new javax.swing.JPanel();
        panelAikon = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        panelBesar.setOpaque(false);
        panelBesar.setPreferredSize(new java.awt.Dimension(1300, 758));
        panelBesar.setLayout(new java.awt.BorderLayout(50, 10));

        panelMetro.setOpaque(false);
        panelMetro.setLayout(new java.awt.CardLayout());
        panelBesar.add(panelMetro, java.awt.BorderLayout.CENTER);

        panelKanan.setLayout(new java.awt.BorderLayout());

        panelLogin.setBackground(new java.awt.Color(255, 153, 0));

        labelLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("Nama yg Login");

        labelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Supervisor-64.png"))); // NOI18N

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addComponent(labelAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKanan.add(panelLogin, java.awt.BorderLayout.NORTH);

        tabbedPane1Verbose.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        textVerbose.setColumns(20);
        textVerbose.setLineWrap(true);
        textVerbose.setRows(5);
        textVerbose.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(textVerbose);

        javax.swing.GroupLayout panelVerboseLayout = new javax.swing.GroupLayout(panelVerbose);
        panelVerbose.setLayout(panelVerboseLayout);
        panelVerboseLayout.setHorizontalGroup(
            panelVerboseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerboseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVerboseLayout.setVerticalGroup(
            panelVerboseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerboseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane1Verbose.addTab("Verbose", panelVerbose);

        panelKanan.add(tabbedPane1Verbose, java.awt.BorderLayout.CENTER);

        panelWaktu.setBackground(new java.awt.Color(255, 153, 0));

        labelWaktu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelWaktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWaktu.setText("Waktu Saat Ini");

        javax.swing.GroupLayout panelWaktuLayout = new javax.swing.GroupLayout(panelWaktu);
        panelWaktu.setLayout(panelWaktuLayout);
        panelWaktuLayout.setHorizontalGroup(
            panelWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWaktu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        panelWaktuLayout.setVerticalGroup(
            panelWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWaktuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelKanan.add(panelWaktu, java.awt.BorderLayout.PAGE_END);

        panelBesar.add(panelKanan, java.awt.BorderLayout.EAST);

        panelMenu.setOpaque(false);
        panelMenu.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setBackground(new java.awt.Color(40, 123, 176));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/header_tutwuri.png"))); // NOI18N
        jLabel1.setOpaque(true);
        panelMenu.add(jLabel1);

        jLabel3.setBackground(new java.awt.Color(40, 123, 176));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/header_dashboardPDPT.png"))); // NOI18N
        jLabel3.setOpaque(true);
        panelMenu.add(jLabel3);

        panelBesar.add(panelMenu, java.awt.BorderLayout.NORTH);

        panelBawah.setOpaque(false);
        panelBawah.setLayout(new javax.swing.BoxLayout(panelBawah, javax.swing.BoxLayout.LINE_AXIS));

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit-64.png"))); // NOI18N
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });
        panelBawah.add(label1);

        panelBesar.add(panelBawah, java.awt.BorderLayout.SOUTH);

        panelKiri.setOpaque(false);
        panelKiri.setLayout(new java.awt.BorderLayout());

        panelAikon.setOpaque(false);
        panelAikon.setLayout(new java.awt.GridLayout(6, 1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database_supermini.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelAikon.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kegiatan_supermini.png"))); // NOI18N
        panelAikon.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data_pendukung_supermini.png"))); // NOI18N
        panelAikon.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evaluasi_utility_supermini.png"))); // NOI18N
        panelAikon.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kependidikan2_supermini.gif"))); // NOI18N
        panelAikon.add(jButton11);
        panelAikon.add(jButton12);

        panelKiri.add(panelAikon, java.awt.BorderLayout.CENTER);

        panelBesar.add(panelKiri, java.awt.BorderLayout.WEST);

        panelBesar.setBounds(0, 0, 1360, 758);
        desktopPane.add(panelBesar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(desktopPane);
        desktopPane.setBounds(0, 0, 1370, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_label1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Component komponen = panelMetro.getComponent(0);
        panelMetro.remove(komponen);        
        inisialisasiLayarTengah();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tampilkanJam() {
        timer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                labelWaktu.setText(new Date().toString());
            }
        });
        timer.start();
    }
    
    private void layarPenuh() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        setPreferredSize(dimension);
    }
    
    public static void main(String [] args) {
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        TanpaBingkai2 coba = new TanpaBingkai2();
        coba.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Widget.Label label1;
    private javax.swing.JLabel labelAvatar;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JPanel panelAikon;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelBesar;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMetro;
    private javax.swing.JPanel panelVerbose;
    private javax.swing.JPanel panelWaktu;
    private javax.swing.JTabbedPane tabbedPane1Verbose;
    private javax.swing.JTextArea textVerbose;
    // End of variables declaration//GEN-END:variables
}
