/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JWindow;

/**
 *
 * @author asus
 */
public class TanpaBingkai extends JWindow {

    /**
     * Creates new form TanpaBingkai
     */
    public TanpaBingkai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        panelBesar = new javax.swing.JPanel();
        panelMetro = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        tabbedPane1Verbose = new javax.swing.JTabbedPane();
        panelVerbose = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelAikon = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelBawah = new javax.swing.JPanel();
        panelKiri = new javax.swing.JPanel();

        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 90, 73, 23);

        panelBesar.setOpaque(false);
        panelBesar.setPreferredSize(new java.awt.Dimension(1300, 758));
        panelBesar.setLayout(new java.awt.BorderLayout(50, 10));

        panelMetro.setOpaque(false);
        panelMetro.setLayout(new java.awt.CardLayout());
        panelBesar.add(panelMetro, java.awt.BorderLayout.CENTER);

        jInternalFrame1.setVisible(true);

        tabbedPane1Verbose.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        javax.swing.GroupLayout panelVerboseLayout = new javax.swing.GroupLayout(panelVerbose);
        panelVerbose.setLayout(panelVerboseLayout);
        panelVerboseLayout.setHorizontalGroup(
            panelVerboseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        panelVerboseLayout.setVerticalGroup(
            panelVerboseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        tabbedPane1Verbose.addTab("Verbose", panelVerbose);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane1Verbose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(tabbedPane1Verbose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBesar.add(jInternalFrame1, java.awt.BorderLayout.EAST);

        panelMenu.setOpaque(false);
        panelMenu.setLayout(new java.awt.GridLayout(1, 3, 50, 150));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelMenu.add(jPanel1);

        panelAikon.setOpaque(false);
        panelAikon.setLayout(new java.awt.GridLayout(1, 6));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database_supermini.png"))); // NOI18N
        panelAikon.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kegiatan_supermini.png"))); // NOI18N
        panelAikon.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data_pendukung_supermini.png"))); // NOI18N
        panelAikon.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evaluasi_utility_supermini.png"))); // NOI18N
        panelAikon.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kependidikan2_supermini.gif"))); // NOI18N
        panelAikon.add(jButton11);
        panelAikon.add(jButton12);

        panelMenu.add(panelAikon);

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelMenu.add(jPanel2);

        panelBesar.add(panelMenu, java.awt.BorderLayout.NORTH);

        panelBawah.setOpaque(false);

        javax.swing.GroupLayout panelBawahLayout = new javax.swing.GroupLayout(panelBawah);
        panelBawah.setLayout(panelBawahLayout);
        panelBawahLayout.setHorizontalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        panelBawahLayout.setVerticalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelBesar.add(panelBawah, java.awt.BorderLayout.SOUTH);

        panelKiri.setOpaque(false);

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        panelBesar.add(panelKiri, java.awt.BorderLayout.WEST);

        panelBesar.setBounds(0, 0, 1360, 758);
        desktopPane.add(panelBesar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(desktopPane);
        desktopPane.setBounds(0, 0, 1370, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void layarPenuh() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        setPreferredSize(dimension);
    }
    
    public static void main(String [] args) {
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        TanpaBingkai coba = new TanpaBingkai();
        coba.setSize(1366, 768);
        //coba.layarPenuh();
        coba.setVisible(true);        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelAikon;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelBesar;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMetro;
    private javax.swing.JPanel panelVerbose;
    private javax.swing.JTabbedPane tabbedPane1Verbose;
    // End of variables declaration//GEN-END:variables
}
