/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromini;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author asus
 */
public class TerminalMetroMini extends javax.swing.JFrame {

    /**
     * Creates new form TerminalMetroMini
     */
    public TerminalMetroMini() {
        initComponents();
        layarPenuh();
    }
    
    private void layarPenuh() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        setPreferredSize(dimension);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        panelBesar = new javax.swing.JPanel();
        panelMetro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        tabbedPane1Verbose = new javax.swing.JTabbedPane();
        panelVerbose = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelAikon = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelBawah = new javax.swing.JPanel();
        panelKiri = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kotak-kotakan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelBesar.setOpaque(false);
        panelBesar.setPreferredSize(new java.awt.Dimension(1300, 758));
        panelBesar.setLayout(new java.awt.BorderLayout(50, 10));

        panelMetro.setOpaque(false);
        panelMetro.setLayout(new java.awt.GridLayout(4, 3, 6, 6));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nama Menu");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelMetro.add(jLabel1);
        panelMetro.add(jLabel2);
        panelMetro.add(jLabel3);

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\database_mini.png")); // NOI18N
        jButton1.setBorder(null);
        panelMetro.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\kegiatan_mini.png")); // NOI18N
        panelMetro.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\data_pendukung_mini.png")); // NOI18N
        panelMetro.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\evaluasi_utility_mini.png")); // NOI18N
        panelMetro.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\kependidikan2.gif")); // NOI18N
        panelMetro.add(jButton5);
        panelMetro.add(jButton6);

        jButton15.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\prev_mini.png")); // NOI18N
        panelMetro.add(jButton15);
        panelMetro.add(jButton14);

        jButton13.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\next_mini.png")); // NOI18N
        jButton13.setOpaque(false);
        panelMetro.add(jButton13);

        panelBesar.add(panelMetro, java.awt.BorderLayout.CENTER);

        jInternalFrame1.setVisible(true);

        tabbedPane1Verbose.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        javax.swing.GroupLayout panelVerboseLayout = new javax.swing.GroupLayout(panelVerbose);
        panelVerbose.setLayout(panelVerboseLayout);
        panelVerboseLayout.setHorizontalGroup(
            panelVerboseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        panelVerboseLayout.setVerticalGroup(
            panelVerboseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        tabbedPane1Verbose.addTab("Verbose", panelVerbose);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane1Verbose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(tabbedPane1Verbose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBesar.add(jInternalFrame1, java.awt.BorderLayout.EAST);

        panelMenu.setOpaque(false);
        panelMenu.setLayout(new java.awt.GridLayout(1, 3, 50, 150));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelMenu.add(jPanel1);

        panelAikon.setOpaque(false);
        panelAikon.setLayout(new java.awt.GridLayout(1, 6));

        jButton7.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\database_supermini.png")); // NOI18N
        panelAikon.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\kegiatan_supermini.png")); // NOI18N
        panelAikon.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\data_pendukung_supermini.png")); // NOI18N
        panelAikon.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\evaluasi_utility_supermini.png")); // NOI18N
        panelAikon.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon("E:\\UTM\\Sep12Feb13\\3.PengabdianMasyarakat\\X-Epsbed\\PDPTClient\\PDPT1\\KotakKotakan\\res\\kependidikan2_supermini.gif")); // NOI18N
        panelAikon.add(jButton11);
        panelAikon.add(jButton12);

        panelMenu.add(panelAikon);

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelMenu.add(jPanel2);

        panelBesar.add(panelMenu, java.awt.BorderLayout.NORTH);

        panelBawah.setOpaque(false);

        javax.swing.GroupLayout panelBawahLayout = new javax.swing.GroupLayout(panelBawah);
        panelBawah.setLayout(panelBawahLayout);
        panelBawahLayout.setHorizontalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        panelBawahLayout.setVerticalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelBesar.add(panelBawah, java.awt.BorderLayout.SOUTH);

        panelKiri.setOpaque(false);

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        panelBesar.add(panelKiri, java.awt.BorderLayout.WEST);

        panelBesar.setBounds(0, 0, 1300, 758);
        desktopPane.add(panelBesar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalMetroMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminalMetroMini().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPanel panelAikon;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelBesar;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMetro;
    private javax.swing.JPanel panelVerbose;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTabbedPane tabbedPane1Verbose;
    // End of variables declaration//GEN-END:variables
}
