/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromenu;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import koneksi.BacaFileTeks;

/**
 *
 * @author asus
 */
public class LoginBox extends javax.swing.JPanel {
    private Bingkai bingkai;
    private koneksi.KoneksiOracleThinClient koneksiDB;
    private String query;
    private String [] data;

    /**
     * Creates new form LoginBox
     */
    public LoginBox(Bingkai _bingkai) {
        bingkai = _bingkai;
        koneksiDB = bingkai.dapatkanKoneksiDB();
        initComponents();
        System.out.println("login box dijalankan");
        data = new String [2]; //utk simpan nama dan password
    }
    
    public void aturFocus() {
        jTextField1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBanner = new javax.swing.JPanel();
        panelAreaLogin = new javax.swing.JPanel();
        panelFrameLogin = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        label1 = new Widget.Label();
        jTextField1 = new javax.swing.JTextField();
        label2 = new Widget.Label();
        jPasswordField1 = new javax.swing.JPasswordField();
        button1 = new Widget.Button();
        button2 = new Widget.Button();
        panelTembelanKiri = new javax.swing.JPanel();
        panelTembelanKanan = new javax.swing.JPanel();
        panelTembelanAtas = new javax.swing.JPanel();
        panelTembelanBawah = new javax.swing.JPanel();
        loginGagalArea = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 2));

        panelBanner.setOpaque(false);
        add(panelBanner);

        panelAreaLogin.setOpaque(false);
        panelAreaLogin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 500));

        panelFrameLogin.setOpaque(false);
        panelFrameLogin.setLayout(new java.awt.BorderLayout());

        panelLogin.setBackground(new java.awt.Color(227, 227, 227));
        panelLogin.setLayout(new java.awt.GridLayout(3, 2, 20, 10));

        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Nama Operator");
        label1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        panelLogin.add(label1);

        jTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 0));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        panelLogin.add(jTextField1);

        label2.setForeground(new java.awt.Color(255, 153, 0));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("Kata Sandi");
        label2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        panelLogin.add(label2);

        jPasswordField1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 153, 0));
        jPasswordField1.setCaretColor(new java.awt.Color(255, 153, 0));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        panelLogin.add(jPasswordField1);

        button1.setBackground(new java.awt.Color(27, 172, 255));
        button1.setForeground(new java.awt.Color(255, 153, 0));
        button1.setMnemonic('B');
        button1.setText("Batal");
        button1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        button1.setOpaque(true);
        button1.setRoundRect(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelLogin.add(button1);

        button2.setBackground(new java.awt.Color(27, 172, 255));
        button2.setForeground(new java.awt.Color(255, 153, 0));
        button2.setMnemonic('L');
        button2.setText("Login");
        button2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        button2.setOpaque(true);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelLogin.add(button2);

        panelFrameLogin.add(panelLogin, java.awt.BorderLayout.CENTER);
        panelFrameLogin.add(panelTembelanKiri, java.awt.BorderLayout.WEST);
        panelFrameLogin.add(panelTembelanKanan, java.awt.BorderLayout.EAST);
        panelFrameLogin.add(panelTembelanAtas, java.awt.BorderLayout.NORTH);

        loginGagalArea.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        loginGagalArea.setForeground(new java.awt.Color(255, 0, 51));
        panelTembelanBawah.add(loginGagalArea);

        panelFrameLogin.add(panelTembelanBawah, java.awt.BorderLayout.SOUTH);

        panelAreaLogin.add(panelFrameLogin);

        add(panelAreaLogin);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "" + evt.getKeyCode());
        if (evt.getKeyCode() == 10) {
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            button2ActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try {
            // TODO add your handling code here:
            System.out.println("Ditekan login");
    //        BacaFileTeks baca = new BacaFileTeks("ip.ip");
    //        String txt = baca.dapatkanData();
    //        System.out.println("nilai "+txt);
            data[0] = jTextField1.getText();
            data[1] = new String(jPasswordField1.getPassword());        
            /*
            query = "SELECT count(*) " + 
                    " FROM FUAD.TMST_USERNAME " + 
                    " WHERE FUAD.TMST_USERNAME.\"Username\" = ? " + 
                    " AND FUAD.TMST_USERNAME.\"Password\" = ? ";
            */
            //koneksiDB.prepareSelectData(query, data);
            
            /*//hanya memeriksa kecocokan antara username dan password
            query = "SELECT count(*) " + 
                    " FROM TMST_USERNAME " + 
                    " WHERE TMST_USERNAME.\"Username\" = '" + data[0] + "' " + 
                    " AND TMST_USERNAME.\"Password\" = '" + data[1] + "' ";
                    * */
            query = "select " + 
                    " count(*) as Ada," +
                    " A.\"Kode_perguruan_tinggi\" as KodePT, " +
                    " A.\"Flag_status_user\" as KodeHak, " +
                    " B.\"Nama_role\" as Pengguna " +
                    " from " +
                    " pdpt_dev.\"TMST_USERNAME\" A, " +
                    " pdpt_dev.\"TREF_ROLE_USER\" B " +
                    " where " +
                    " A.\"Username\"='" + data[0] + "' " +
                    " and A.\"Password\"='" + data[1] + "' " +
                    " and A.\"Flag_status_user\" = B.\"Kode_role_user\" " +
                    " group by " +
                    " A.\"Kode_perguruan_tinggi\", " +
                    " A.\"Flag_status_user\", " +
                    " B.\"Nama_role\"";
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            md.update(data[1].getBytes());
     
            byte byteData[] = md.digest();
     
            //convert the byte to hex format method 1
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < byteData.length; i++) {
             sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
            }
     
            System.out.println("Digest(in hex format):: " + sb.toString());
     
            //convert the byte to hex format method 2
            StringBuffer hexString = new StringBuffer();
                for (int i=0;i<byteData.length;i++) {
                        String hex=Integer.toHexString(0xff & byteData[i]);
                            if(hex.length()==1) hexString.append('0');
                            hexString.append(hex);
                }
                String pass = hexString.toString();
                System.out.println("Digest(in hex format):: " + hexString.toString());
        
            
//            query = "select " + 
//                    " count(*) as Ada," +
//                    " A.\"unit\" as KodePT, " +
//                    " A.\"level_id\" as KodeHak, " +
//                    " A.\"nama\" as Pengguna " +
//                    " from " +
//                    " administrasi.\"users\" A, " +
//                    " administrasi.\"levels\" B " +
//                    " where " +
//                    " A.\"username\"='" + data[0] + "' " +
//                    " and A.\"password\"='" + pass + "' " +
//                    " and A.\"level_id\" = B.\"id\" " +
//                    " group by " +
//                    " A.\"level_id\", " +
//                    " A.\"unit\", " +
//                    " A.\"nama\"";
            
            koneksiDB.selectData(query);
            System.out.println("query: " + query);
            
            //int hasil = koneksiDB.dapatkanJumlahRecordYangDicari();//cara lama hanya memeriksa kemunculan 1 record dgn kecocokan username & password
            //try{
                String [][] dataValidasi = koneksiDB.dapatkanData();
                System.out.println("dataValidasi: " + dataValidasi[0][0]);
                if (dataValidasi[0][0]==null) {
                    System.out.println("loginGagal dimunculkan");
                    loginGagalArea.setText("Nama/sandi tidak dikenali");
                    jTextField1.selectAll();
                    jPasswordField1.selectAll();
                    jTextField1.requestFocus();
                } 
                else {
                    int hasil = Integer.parseInt(dataValidasi[0][0]);
                    String kodeperguruantinggi = dataValidasi[0][1];
                    String koderole = dataValidasi[0][2];
                    String namarole = dataValidasi[0][3];
                    System.out.println("hasil = " + hasil);

                    if (hasil == 1) { //hanya bisa dipakai sebelum tgl 17 des 2012, dikomen utk keperluan laporan 3 des 2012
                        int intKoderole = 0;
                        if (koderole != null) {
                            intKoderole = Integer.parseInt(koderole);
                            System.out.println("kode role = " + intKoderole);
                        }
                        if (intKoderole == 3 || intKoderole == 1) {//kamis,17jan2013@DIKTI
                            try {                    
                                bingkai.simpanKodePT(kodeperguruantinggi); //ditambahkan sabtu, 22 des 2012 @krembangan 22.53
                                bingkai.simpanNamaRole(namarole);

                                bingkai.panelBerikutnya("home");
                            } catch (SQLException ex) {
                                Logger.getLogger(LoginBox.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        if (intKoderole == 3 || intKoderole == 2) {//kamis,17jan2013@DIKTI
                            loginGagalArea.setText("Anda tidak diperkenankan mengakses sistem");
                        }
                   }

                }
            /*}catch (NumberFormatException n){
                if (n.equals(null)) {
                    loginGagalScrollPane.setVisible(true);
                    loginGagalArea.setText("Nama operator atau kata sandi tidak dikenali sistem");
                }
            }*/
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(LoginBox.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button2ActionPerformed

    public String [] dapatkanUserPassword() {
        return data;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Widget.Button button1;
    private Widget.Button button2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private Widget.Label label1;
    private Widget.Label label2;
    private javax.swing.JLabel loginGagalArea;
    private javax.swing.JPanel panelAreaLogin;
    private javax.swing.JPanel panelBanner;
    private javax.swing.JPanel panelFrameLogin;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelTembelanAtas;
    private javax.swing.JPanel panelTembelanBawah;
    private javax.swing.JPanel panelTembelanKanan;
    private javax.swing.JPanel panelTembelanKiri;
    // End of variables declaration//GEN-END:variables
}
