/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * GUNAKAN INI HANYA JIKA WAKTU DEVELOPING CUKUP LAMA
 */
package metromenu;

import Widget.Button;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonModel;
import javax.swing.JTextField;

/**
 *
 * @author asus
 */
public class MenuDosen extends javax.swing.JPanel {    
    private String [] judulMenuUtama = {"Dosen", "Mahasiswa", "Institusi"};
    private String [] aikonMenuUtama = {
        "/image/Dosen64.png",
        "/image/Mahasiswa64.png",
        "/image/Institusi64.png"
    };
    private String [] judulMenuDosen = {
        "<HTML>\nMaster<BR>\nDosen\n</HTML>",
        "<HTML>\nAktivitas<BR>\nMengajar<BR>\nDosen\n</HTML>",
        "<HTML>\nAnggota<BR>\nPeneliti<BR>\nAhli\n</HTML>",
        "<HTML>\nAnggota<BR>\nPeneliti<BR>\nDukung\n</HTML>",
        "<HTML>\nAnggota<BR>\nPenelitian<BR>\nDosen\n</HTML>",
        "<HTML>\nFTE<BR>\nDosen\n</HTML>",
        "<HTML>\nHKI\n</HTML>",
        "<HTML>\nKinerja<BR>\nDosen\n</HTML>",
        "<HTML>\nPublikasi<BR>\nDosen<BR>\nTetap\n</HTML>",
        "<HTML>\nRiwayat<BR>\nPendidikan<BR>\nDosen\n</HTML>",
        "<HTML>\nRiwayat<BR>\nStatus<BR>\nDosen\n</HTML>",
        "<HTML>\nTenaga<BR>\nAhli\n</HTML>",
        "<HTML>\nTenaga<BR>\nPendukung\n</HTML>"
    };    
    private String [] aikonMenuDosen = {
        "/image/dosen/MasterDosen64.png",
        "/image/dosen/AktivitasMengajarDosen64.png",
        "/image/dosen/AnggotaPenelitiAhli64.png",
        "/image/dosen/AnggotaPenelitiPendukung64.png",
        "/image/dosen/AnggotaPenelitianDosen64.png",
        "/image/dosen/FTEDosen64.png",
        "/image/dosen/HKI64.png",
        "/image/dosen/KinerjaDosen64.png",
        "/image/dosen/PublikasiDosenTetap64.png",
        "/image/dosen/RiwayatPendidikanDosen64.png",
        "/image/dosen/RiwayaStatusDosen64.png",
        "/image/dosen/TenagaAhli64.png",
        "/image/dosen/TenagaPendukung64.png"
    };
    private int counterMenuUtama = 0; //item di root menu 
    private int counterSubMenu = 0;  //item di sub menu
    private int counterLevel = 0; //level 0=root menu, 1=sub menu
    private int counterPaging = -1; //-1=sebelum page 1, 0=page 1, 1=page 2
    private int menuYgDipilih = 0;
    private MemilihActionListener listener;
    
    class MemilihActionListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {             
            String aksi = e.getActionCommand();
            menuYgDipilih = Integer.parseInt("" + aksi.charAt(aksi.length()-1));
            System.out.println("menu yg dipilih: " + menuYgDipilih);
            if (counterLevel == 0) { //jika root menu dipilih
                counterMenuUtama = menuYgDipilih - 1;
                if (counterMenuUtama == 0) { //jika menu Dosen dipilih
                    Component [] komponens = panelMenu.getComponents();
                    int indeks = 0;
                    for (Component komponen: komponens) {
                        if (komponen.getClass().getSimpleName().equals("Button")) {
                            ((Button)komponen).setIcon(
                                new javax.swing.ImageIcon(getClass().
                                    getResource(aikonMenuDosen[indeks]))); // NOI18N
                            ((Button)komponen).setText(judulMenuDosen[indeks]);
                        }
                        indeks++;
                    }
                    counterPaging = 0; //page 1 dari sub menu Dosen 
                }
            }
        }
    }
    
    private void inisialisasiAksi() {
        listener = new MemilihActionListener();
        Component [] komponens = panelMenu.getComponents();
        for (Component komponen: komponens) {
            if (komponen.getClass().getSimpleName().equals("Button")) {
                ((Button)komponen).addActionListener(listener);
                System.out.println("menambahkan listener ke " + 
                        ((Button)komponen).getActionCommand());
            }
        }
    }

    /**
     * Creates new form MenuDosen
     */
    public MenuDosen() {
        initComponents();
        inisialisasiAksi();
        updatePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonMenu1 = new Widget.Button();
        buttonMenu2 = new Widget.Button();
        buttonMenu3 = new Widget.Button();
        buttonMenu4 = new Widget.Button();
        buttonMenu5 = new Widget.Button();
        buttonMenu6 = new Widget.Button();
        panelNavigasi = new javax.swing.JPanel();
        panelPrev = new javax.swing.JPanel();
        buttonMenuPrev = new Widget.Button();
        panelKosong = new javax.swing.JPanel();
        panelNext = new javax.swing.JPanel();
        buttonMenuNext = new Widget.Button();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelMenu.setOpaque(false);
        panelMenu.setLayout(new java.awt.GridLayout(2, 3));

        buttonMenu1.setActionCommand("menu1");
        buttonMenu1.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        panelMenu.add(buttonMenu1);

        buttonMenu2.setActionCommand("menu2");
        buttonMenu2.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        panelMenu.add(buttonMenu2);

        buttonMenu3.setActionCommand("menu3");
        buttonMenu3.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        panelMenu.add(buttonMenu3);

        buttonMenu4.setActionCommand("menu4");
        buttonMenu4.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        panelMenu.add(buttonMenu4);

        buttonMenu5.setActionCommand("menu5");
        buttonMenu5.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        panelMenu.add(buttonMenu5);

        buttonMenu6.setActionCommand("menu6");
        buttonMenu6.setFont(new java.awt.Font("Tw Cen MT", 0, 22)); // NOI18N
        panelMenu.add(buttonMenu6);

        add(panelMenu, java.awt.BorderLayout.CENTER);

        panelNavigasi.setOpaque(false);
        panelNavigasi.setLayout(new java.awt.BorderLayout());

        panelPrev.setOpaque(false);

        buttonMenuPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/prev_mini.png"))); // NOI18N
        buttonMenuPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrevLayout = new javax.swing.GroupLayout(panelPrev);
        panelPrev.setLayout(panelPrevLayout);
        panelPrevLayout.setHorizontalGroup(
            panelPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrevLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonMenuPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPrevLayout.setVerticalGroup(
            panelPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMenuPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelNavigasi.add(panelPrev, java.awt.BorderLayout.WEST);

        panelKosong.setOpaque(false);

        javax.swing.GroupLayout panelKosongLayout = new javax.swing.GroupLayout(panelKosong);
        panelKosong.setLayout(panelKosongLayout);
        panelKosongLayout.setHorizontalGroup(
            panelKosongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        panelKosongLayout.setVerticalGroup(
            panelKosongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelNavigasi.add(panelKosong, java.awt.BorderLayout.CENTER);

        panelNext.setOpaque(false);

        buttonMenuNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next_mini.png"))); // NOI18N
        buttonMenuNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNextLayout = new javax.swing.GroupLayout(panelNext);
        panelNext.setLayout(panelNextLayout);
        panelNextLayout.setHorizontalGroup(
            panelNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNextLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonMenuNext, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNextLayout.setVerticalGroup(
            panelNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMenuNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelNavigasi.add(panelNext, java.awt.BorderLayout.EAST);

        add(panelNavigasi, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuPrevActionPerformed
        // TODO add your handling code here:tombol Prev
        if (counterLevel == 0) {
            if (counterMenuUtama > 0) {            
                counterMenuUtama--;            
                updatePanel();        
            }
        } else if (counterLevel == 1) {
            if (counterPaging > 0) {            
                counterPaging--;            
                updatePanel();        
            }
        }
    }//GEN-LAST:event_buttonMenuPrevActionPerformed

    private void buttonMenuNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuNextActionPerformed
        // TODO add your handling code here:tombol Next
        if (counterLevel == 0) { //jika root menu dipilih
            if (counterMenuUtama < judulMenuUtama.length - 1) {            
                //jawaban[counterSubMenu] = txtJawaban.getText().charAt(0);
                counterMenuUtama++;
                updatePanel();        
            }
        } else if (counterLevel == 1) { //jika sub menu dipilih
            if (counterMenuUtama == 0) { //jika sebelumnya root menu item 1=Dosen dipilih
                int jumlahPage = judulMenuDosen.length / 6;
                if ( (judulMenuDosen.length % 6) >= 1 ) jumlahPage++;
                if (counterPaging < jumlahPage) {            
                    counterPaging++;
                    updatePanel();        
                }
            }
        }        
    }//GEN-LAST:event_buttonMenuNextActionPerformed

    private void updatePanel() {
        //pengaturan tampilan menu
        if (counterLevel == 0) {
            buttonMenu1.setIcon(
                            new javax.swing.ImageIcon(getClass().getResource(
                              aikonMenuUtama[0]))); // NOI18N
            buttonMenu1.setText(judulMenuUtama[0]);
            buttonMenu2.setIcon(
                            new javax.swing.ImageIcon(getClass().getResource(
                              aikonMenuUtama[1]))); // NOI18N
            buttonMenu2.setText(judulMenuUtama[1]);
            buttonMenu3.setIcon(
                            new javax.swing.ImageIcon(getClass().getResource(
                              aikonMenuUtama[2]))); // NOI18N
            buttonMenu3.setText(judulMenuUtama[2]);
        }
        if (counterLevel == 1) {
            Component [] komponens = panelMenu.getComponents();
            int indeks = 0;
            for (Component komponen: komponens) {
                System.out.println("class " + 
                        komponen.getClass().getSimpleName() + ":" +
                        ((Button)komponen).getActionCommand()
                        );
                String actionCommand = ((Button)komponen).getActionCommand();
                int indeksMenu = Integer.parseInt("" + actionCommand.charAt(actionCommand.length()));
                
                if (komponen.getClass().getSimpleName().equals("Button") &&  indeksMenu < 4) {                
                    ((Button)komponen).setIcon(
                            new javax.swing.ImageIcon(getClass().getResource(
                              aikonMenuUtama[indeks]))); // NOI18N
                    ((Button)komponen).setText(judulMenuUtama[indeks]);
                    //System.out.println("data yg disimpan: " + data[indeks]);
                    indeks++;
                } 
                
                
            }
        }
        
        //pengaturan enabelisitas tombol navigasi
        aturEnabelisitasTombolNavigasi();
    }
    
    private void aturEnabelisitasTombolNavigasi() {
        //pengaturan enabelisitas tombol navigasi
        if (counterLevel == 0) { //jika root menu dibuka
            buttonMenuNext.setEnabled(false); //Next
            buttonMenuPrev.setEnabled(false); //Prev
        }
        else if (counterLevel == 1) { //jika root menu item 1 dipilih sehingga sub menunya terbuka
            if (counterMenuUtama == 0) { //jika sub menu Dosen terbuka
                if (counterPaging > 0) buttonMenuPrev.setEnabled(true);
                else buttonMenuPrev.setEnabled(false);

                int jumlahPage = judulMenuDosen.length / 6;
                if ( (judulMenuDosen.length % 6) >= 1 ) jumlahPage++;
                if (counterPaging > jumlahPage) buttonMenuPrev.setEnabled(false);
                else buttonMenuPrev.setEnabled(true);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Widget.Button buttonMenu1;
    private Widget.Button buttonMenu2;
    private Widget.Button buttonMenu3;
    private Widget.Button buttonMenu4;
    private Widget.Button buttonMenu5;
    private Widget.Button buttonMenu6;
    private Widget.Button buttonMenuNext;
    private Widget.Button buttonMenuPrev;
    private javax.swing.JPanel panelKosong;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNavigasi;
    private javax.swing.JPanel panelNext;
    private javax.swing.JPanel panelPrev;
    // End of variables declaration//GEN-END:variables
}
