/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metromenu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author asus
 */
public class SplashCologne extends javax.swing.JPanel {
    private Bingkai bingkai;
    private Timer timer;
    private static int counter = 0;

    /**
     * Creates new form SplashCologne
     */
    public SplashCologne(Bingkai _bingkai) {
        this.bingkai = _bingkai;
        initComponents();
        inisialisasiLabel();
        tampilkanJam();
//        labelAksesData.setVisible(false);
//        labelT.setVisible(false);
    }
    
    private void inisialisasiLabel() {
        labelP1.setText("");
        labelP1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                
        labelD.setText("");
        labelD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        
        labelP2.setText("");
        labelP2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        
        labelT.setText("");
        labelT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        
        labelAksesData.setText("");
        labelAksesData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        
        //ditambahkan sabtu,29 des2012
        labelDIKTI.setText("");
        labelDIKTI.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        labelDIKTI.setOpaque(false);                
    }
    
    private void tampilkanJam() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("counter = " + counter);
                if (counter==0) {
                    labelP1.setText("Sistem Informasi");
//                    labelP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));
                }
                if (counter==1) {
                    labelD.setText("Manajemen Pelaporan");
//                    labelD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));
                }
                if (counter==2) {
                    labelP2.setText("PDPT");
                    labelP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));
                }
                if (counter==3) {
//                    labelT.setText("T");
//                    labelT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));
//                     ImageIcon image = new ImageIcon("/image/Insert documents-64.png");
                    labelT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tutwuri_handayani256.png")));
                }
                if (counter==4) {
//                    ImageIcon image = new ImageIcon("/image/Insert documents-64.png");
//                    labelAksesData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ieu.jpg")));
                    labelAksesData.setText("SIMPEL PDPT");
                }
                if (counter==5) {
                    labelDIKTI.setText("PT");
                    labelDIKTI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,153,0), 5, true));
                    labelDIKTI.setOpaque(true);
                }
                if (counter == 6) {
                    try {                    
                        selesai();
                    } catch (SQLException ex) {
                        Logger.getLogger(SplashCologne.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }             
                counter++;
                jProgressBar1.setValue(counter * 20);
            }
        });
        timer.start();        
    }
    
    private void selesai() throws SQLException {
        if (timer.isRunning()) {            
            timer.stop();            
            bingkai.panelBerikutnya("login");
            if (timer.isRunning() == false) {
                System.out.println("timer distop, login dimulai");
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelP1 = new javax.swing.JLabel();
        labelAksesData = new javax.swing.JLabel();
        labelD = new javax.swing.JLabel();
        labelP2 = new javax.swing.JLabel();
        labelT = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        labelDIKTI = new javax.swing.JLabel();

        setOpaque(false);

        labelP1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 125)); // NOI18N
        labelP1.setForeground(new java.awt.Color(255, 153, 0));
        labelP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelP1.setText("Informasi");
        labelP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));

        labelAksesData.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 120)); // NOI18N
        labelAksesData.setForeground(new java.awt.Color(255, 153, 0));
        labelAksesData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAksesData.setText("Akses Data");

        labelD.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 150)); // NOI18N
        labelD.setForeground(new java.awt.Color(255, 153, 0));
        labelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelD.setText("Dan");
        labelD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));

        labelP2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 200)); // NOI18N
        labelP2.setForeground(new java.awt.Color(255, 153, 0));
        labelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelP2.setText("Pelaporan");
        labelP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));

        labelT.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 300)); // NOI18N
        labelT.setForeground(new java.awt.Color(255, 153, 0));
        labelT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT.setText("T");
        labelT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));

        labelDIKTI.setBackground(new java.awt.Color(255, 153, 0));
        labelDIKTI.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 80)); // NOI18N
        labelDIKTI.setForeground(new java.awt.Color(51, 84, 111));
        labelDIKTI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDIKTI.setText("PT");
        labelDIKTI.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelD, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelT, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelAksesData, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDIKTI, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelD, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAksesData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDIKTI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel labelAksesData;
    private javax.swing.JLabel labelD;
    private javax.swing.JLabel labelDIKTI;
    private javax.swing.JLabel labelP1;
    private javax.swing.JLabel labelP2;
    private javax.swing.JLabel labelT;
    // End of variables declaration//GEN-END:variables
}
